title: Theo Munoz
##Image
logo: assets/img/Headshot (1).png
#Desciption of Image
#description: Theo Munoz
show downloads: False
#Theme of the Page
theme: jekyll-theme-minimal


# Link to GitHub repository
github_url: https://github.com/theompe95/ds_portafolio.git
